#!/usr/bin/perl

# Copyright 2021-2023 Citrix Systems, Inc.  All rights reserved.
# Use of this software is governed by the license terms, if any,
# which accompany or are included with this software.

$ENV{PATH} = '/var/python/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'.$ENV{PATH};

use File::Basename;

# checking if python and ply are present
# Output would be /var/python/bin/python if python is
# present, otherwise output would be empty string.
my $python_version_string = `which python 2> /dev/null`;
if ($python_version_string eq "") {
	# Python2 is not installed
	print "\nAs python is not present, we can't check for an invalid configuration\n";
	exit;
}

my $python_module_list = `python -m pip freeze 2> /dev/null`;
if (!($python_module_list =~ m/\bply==/)) {
	# ply is not present
	print "\nAs required module PLY is not present, we can't check for an invalid configuration\n";
	exit;
}


my $number_args = $#ARGV + 1;
if ($number_args != 1) {
    print "Usage: check_invalid_config <ns_config_file>\n";
    exit;
}

my $config_file = $ARGV[0];
if (not -e $config_file) {
    print "No such file: $config_file\n";
    exit;
}

my($filename, $dir_path) = fileparse($config_file);

my $exit_status = system("python /netscaler/nspepi2/config_check_main.py -f $config_file");
if ($exit_status != 0) {
	print "Error in checking config file: $exit_status";
	exit;
}
my $invalid_config_file = $dir_path."/issues_".$filename;

# Checks whether any command is present in the file
if (!(-z $invalid_config_file)) {
	print "\nThe following configuration lines will get errors in 13.1 and both they and dependent configuration will be removed from the configuration:\n";
	system("cat $invalid_config_file");
	print "\nThe nspepi upgrade tool can be useful in converting your configuration - see the documentation at https://docs.citrix.com/en-us/citrix-adc/current-release/appexpert/policies-and-expressions/introduction-to-policies-and-exp/converting-policy-expressions-nspepi-tool.html.\n";
	print "\nNOTE: the nspepi tool doesn't convert the following configurations:\n\t1. SureConnect commands\n\t2. PriorityQueuing commands\n\t3. HTTP Denial of Service Protection commands\n\t4. Classic SSL commands\n\t5. HTMLInjection commands.\n";
} else {
	print "\nNo issue detected with the configuration.\n";
}
print "\nUse pre-validation tool and nspepi tool available at https://github.com/citrix/ADC-scripts/tree/master/nspepi for the most complete and up-to-date version.\n"
### End check_invalid_config script
